### ISSUE TITLE
Setup failed for indego: unknown error

### ISSUE THREAD

**Issue by galex80** [jm-73/Indego#109]
Since the latest update of Home Assistant 0.113.0 (HassOS 4.11) , the following error appears in log-file. Also all entities appear as "unavailable"

Logger: homeassistant.setup
Source: custom_components/indego/__init__.py:37
First occurred: 10:41:28 AM (1 occurrences)
Last logged: 10:41:28 AM

```
Setup failed for indego: unknown error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3030, in _dep_map
    return self.__dep_map
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2824, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3021, in _parsed_pkg_info
    return self._pkg_info
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2824, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 145, in _async_setup_component
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 313, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/indego/__init__.py", line 37, in <module>
    from pyIndego import IndegoAsyncClient
  File "/usr/local/lib/python3.8/site-packages/pyIndego/__init__.py", line 6, in <module>
    __version__ = get_distribution(dist_name).version
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 480, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 356, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 899, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 793, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2745, in requires
    dm = self._dep_map
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3032, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3041, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3023, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1420, in get_metadata
    value = self._get(path)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1626, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/site-packages/urllib3-1.25.9.dist-info/METADATA'
```

**Comment by jm-73** [comment]
I also got this error when upgrading. A reboot solved the issue. Try that and write your result here.

**Comment by galex80** [comment]
> I also got this error when upgrading. A reboot solved the issue. Try that and write your result here.

Indeed, a reboot solved this issue. 
Thank you for that hint. 

Btw: Thanks for your great work so far. Any chance to buy you a coffee? :-)

**Comment by jm-73** [comment]
Great!
Of course, thanks for asking:
https://www.buymeacoffee.com/jm73

**Comment by galex80** [comment]
> Great!
> Of course, thanks for asking:
> https://www.buymeacoffee.com/jm73

Enjoy your coffee :-)
