### ISSUE TITLE
Battery not showing despite working for over a year

### ISSUE THREAD

**Issue by Siggy101** [jm-73/Indego#122]
Logger: homeassistant.components.sensor
Source: custom_components/indego/sensor.py:125
Integration: Sensor (documentation, issues)
First occurred: 19:01:37 (2 occurrences)
Last logged: 19:01:37

Error adding entities for domain sensor with platform indego
Error while setting up indego platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 514, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 546, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/indego/sensor.py", line 68, in async_added_to_hass
    self.state = state.state
  File "/config/custom_components/indego/sensor.py", line 97, in state
    self.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 457, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 310, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 354, in _async_write_ha_state
    icon = (entry and entry.icon) or self.icon
  File "/config/custom_components/indego/sensor.py", line 125, in icon
    int(self._state) if self._state is not None else None, self.charging
ValueError: invalid literal for int() with base 10: 'unknown'

**Comment by Siggy101** [comment]
Ah wait, I think it just fixed itself.
I went to the mower and it was unresponsive, despite the official app suggesting it was fine.
A quick reboot and she's back online in HA.
Is it a coincidence that I also got a software update notification? The first in over a year.....  Fishy.

**Comment by Siggy101** [comment]
She magically healed herself. It was not a fault in the integration but my mower acting up.
