### ISSUE TITLE
Unable to prepare setup for platform indego.sensor: Unable to set up component.

### ISSUE THREAD

**Issue by xguitoux** [jm-73/Indego#140]
Hello, brand new owner of a 350S+ I fail to integrate it in HASS

Version
core-2021.7.4
supervisor-2021.06.8

I got 2 errors in logs 

Logger: homeassistant.setup
Source: setup.py:311
First occurred: 11:48:41 (1 occurrences)
Last logged: 11:48:41

Unable to prepare setup for platform indego.sensor: Unable to set up component.

-------------------------
Error during setup of component indego
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 249, in _async_setup_component
    result = await task
  File "/config/custom_components/indego/__init__.py", line 210, in async_setup
    conf = config[DOMAIN]
KeyError: 'indego'

Thank you for your help

**Comment by xguitoux** [comment]
Auto answer for closing the topic 👍 
I moved the integration config in my sensor.yaml and it wasn't working here.

Moving it back to the main configuration.yaml did the trick.
