### ISSUE TITLE
Error config_entry_oauth2_flow.py

### ISSUE THREAD

**Issue by JeedHome44** [jm-73/Indego#187]
Hello,

All work normally but since 3 days, I have this problem:

![image](https://github.com/jm-73/Indego/assets/41892950/eeec80c6-fcd1-4f4b-b936-e20d100b4a28)

**Comment by JeedHome44** [comment]
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/indego/__init__.py", line 224, in async_setup_entry
    await indego_hub.update_generic_data_and_load_platforms(load_platforms)
  File "/config/custom_components/indego/__init__.py", line 369, in update_generic_data_and_load_platforms
    generic_data = await self._update_generic_data()
  File "/config/custom_components/indego/__init__.py", line 619, in _update_generic_data
    await self._indego_client.update_generic_data()
  File "/usr/local/lib/python3.10/site-packages/pyIndego/indego_async_client.py", line 262, in update_generic_data
    self._update_generic_data(await self.get(f"alms/{self.serial}"))
  File "/usr/local/lib/python3.10/site-packages/pyIndego/indego_async_client.py", line 546, in get
    return await self._request(method=Methods.GET, path=path, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/pyIndego/indego_async_client.py", line 477, in _request
    self._token = await self._token_refresh_method()
  File "/config/custom_components/indego/__init__.py", line 329, in async_token_refresh
    await session.async_ensure_token_valid()
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 499, in async_ensure_token_valid
    new_token = await self.implementation.async_refresh_token(self.token)
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 92, in async_refresh_token
    new_token = await self._async_refresh_token(token)
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 182, in _async_refresh_token
    new_token = await self._token_request(
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 209, in _token_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://prodindego.b2clogin.com/prodindego.onmicrosoft.com/b2c_1a_signup_signin/oauth2/v2.0/token')`

**Comment by JeedHome44** [comment]
Nobody have the same problem ?

**Comment by JeedHome44** [comment]
i delete integration and add integration. it's work now.
