### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by urbatecte** [jm-73/Indego#20]
Hi,
First install of release 0.7 on HA 0.97.2 and I have the followinf error 
2019-08-19 21:49:09 ERROR (MainThread) [homeassistant.setup] Error during setup of component indego
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 172, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/indego/__init__.py", line 54, in setup
    Mower()
  File "/config/custom_components/indego/__init__.py", line 93, in __init__
    IndegoAPI_Instance = IndegoAPI(GLOB_MOWER_USERNAME, GLOB_MOWER_PASSWORD, GLOB_MOWER_SERIAL)
  File "/usr/local/lib/python3.7/site-packages/pyIndego/__init__.py", line 191, in __init__
    self.login()
  File "/usr/local/lib/python3.7/site-packages/pyIndego/__init__.py", line 201, in login
    _LOGGER.debug("JSON Response: " + str(self._login_session.json()))
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-08-19 21:49:09 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=persistent_notification, service=create, service_data=title=New devices discovered, message=We have discovered new devices on your network. [Check it out](/config/integrations), notification_id=config_entry_discovery>
2019-08-19 21:49:09 INFO (SyncWorker_5) [homeassistant.loader] Loaded sensor from homeassistant.components.sensor
2019-08-19 21:49:09 INFO (SyncWorker_6) [homeassistant.loader] Loaded switch from homeassistant.components.switch
2019-08-19 21:49:09 INFO (MainThread) [homeassistant.setup] Setting up auth
2019-08-19 21:49:09 INFO (MainThread) [homeassistant.setup] Setup of domain auth took 0.0 seconds.
2019-08-19 21:49:09 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event component_loaded[L]: component=auth>
2019-08-19 21:49:09 INFO (MainThread) [homeassistant.setup] Setting up system_health
2019-08-19 21:49:09 INFO (MainThread) [homeassistant.setup] Setup of domain system_health took 0.0 seconds.
2019-08-19 21:49:09 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event component_loaded[L]: component=system_health>
2019-08-19 21:49:13 INFO (MainThread) [homeassistant.setup] Setting up api
2019-08-19 21:49:13 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event config_entry_discovered[L]>
2019-08-19 21:49:13 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=persistent_notification, service=create, service_data=title=Invalid config, message=The following components and platforms could not be set up:

 - [indego](https://home-assistant.io/components/indego/)

For information, I have an error 401 on http://grauonline.de/alexwww/indego/indego.html but it was ok few month ago. I've post a comment on this site as well.

Regards,

**Comment by jm-73** [comment]
I have no idea what this culd be. It doesnt seem like it has to do with this component if you also get a 401 on the grauonline interface.
Have you restarted? Tried with another HA? Maybe try with a new installation?

**Comment by urbatecte** [comment]
Actually everthing work as usual. Just need to fill my email instead of username.
Sorry for posting false issue.

Best regards,
urbatecte

**Comment by jm-73** [comment]
NP! Glad it worked out for you!
