### ISSUE TITLE
Can’t update mower_state release 0.3

### ISSUE THREAD

**Issue by onkelfarmor** [jm-73/Indego#3]
Release 0.3:

Update for sensor.indego_mower_state fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 380, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/indego/sensor.py", line 83, in update
    self._serial = API.getSerial()
AttributeError: 'IndegoAPI' object has no attribute 'getSerial'

**Comment by onkelfarmor** [comment]
Downloaded from releases instead, and now it seems to work.
