### ISSUE TITLE
Error during setup of component indego

### ISSUE THREAD

**Issue by simonk1969** [jm-73/Indego#45]
I'm new to HA and have just installed this component but am getting the errors below.
I've tried 0.7.3 and 0.7.4 with same results.

2019-09-21 09:20:38 ERROR (MainThread) [homeassistant.setup] Error during setup of component indego
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 172, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/indego/__init__.py", line 54, in setup
    Mower()
  File "/config/custom_components/indego/__init__.py", line 94, in __init__
    IndegoAPI_Instance = IndegoAPI(GLOB_MOWER_USERNAME, GLOB_MOWER_PASSWORD, GLOB_MOWER_SERIAL)
  File "/usr/local/lib/python3.7/site-packages/pyIndego/__init__.py", line 194, in __init__
    self.login()
  File "/usr/local/lib/python3.7/site-packages/pyIndego/__init__.py", line 204, in login
    _LOGGER.debug("JSON Response: " + str(self._login_session.json()))
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by jm-73** [comment]
I think this errror is thrown when the component doesnt get any answer from the Bosch servers. This error will be handled in the next release!

**Comment by jm-73** [comment]
Fixed in 0.8
