### ISSUE TITLE
Invalid config after setup indego

### ISSUE THREAD

**Issue by galex80** [jm-73/Indego#57]
The following integrations and platforms could not be set up:
indego
Please check your config
With the previous version 0.7.4 it was working, now this error appears in log:
Source: custom_components/indego/__init__.py:135
First occurred: 9:54:43 AM (1 occurrences)
Last logged: 9:54:43 AM

Error during setup of component indego
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 175, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/indego/__init__.py", line 54, in setup
    Mower()
  File "/config/custom_components/indego/__init__.py", line 135, in __init__
    IndegoAPI_Instance.getNextCutting()
  File "/usr/local/lib/python3.7/site-packages/pyIndego/__init__.py", line 511, in getNextCutting
    tmp_datetime = tmp_json['mow_next']
TypeError: 'NoneType' object is not subscriptable

Device in use: Indego 400 connect with latest firmware version
I've checked the configuration multiple times. And the same configuration was working before the update to the latest version.

**Comment by Shamshala** [comment]
Try to turn on SmartMowing mode and let the app to generate the date for next mow, then restart the HA.

**Comment by galex80** [comment]
After activating the SmartMowing, it works. But when i deactivate the function again, the same error occures.

**Comment by norcon** [comment]
Same here.

**Comment by jm-73** [comment]
Release 0.9 should fix this issue. Released today.
