### ISSUE TITLE
0.5 2019-08-11 error during setup of component indego

### ISSUE THREAD

**Issue by onkelfarmor** [jm-73/Indego#7]
The new version gives me this error:

```
Error during setup of component indego
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 172, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/indego/__init__.py", line 54, in setup
    Mower()
  File "/config/custom_components/indego/__init__.py", line 98, in __init__
    IndegoAPI_Instance.getGenericData()
  File "/usr/local/lib/python3.7/site-packages/pyIndego/__init__.py", line 355, in getGenericData
    self._alm_name = tmp_json['alm_name']
KeyError: 'alm_name'
```

**Comment by jm-73** [comment]
Try the following:
In file `indego/manifest.json,` change:
`"requirements": ["pyIndego==0.2.7"]`
to
`"requirements": ["pyIndego==0.2.8"]`

Remove pycache and reboot!
Still seems like your HA isnt able to collect all data correctly from API. This fixes better error/input handling and hopeflly your component will boot and we can get some logs to look at.

**Comment by onkelfarmor** [comment]
Both solutions worked 👍
