### ISSUE TITLE
Error nonetype during init.

### ISSUE THREAD

**Issue by eavanvalkenburg** [jm-73/Indego#74]
I got this error today:
```
2020-06-12 12:43:02 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/indego/__init__.py", line 191, in refresh_1m
    IndegoAPI_Instance.getState()
  File "/usr/local/lib/python3.7/site-packages/pyIndego/__init__.py", line 424, in getState
    self._mower_state = tmp_json.get('state')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by dykandDK** [comment]
I'm can confirm seeing a similar error after upgrading to version 1.2:

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 295, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 446, in _async_add_entity
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 297, in async_write_ha_state
    self._async_write_ha_state()  # type: ignore
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    state = self.state
  File "/config/custom_components/indego/sensor.py", line 256, in state
    if (self._IAPI._battery_percent > self._battery_percent_max):
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'

**Comment by jm-73** [comment]
This is two different bugs.
@eavanvalkenburg  
The first one seems to be related to the Integration not getting answers from API. Wrong password? Shaky internet? Bosch servers not answering?
I would be interested in your debug log to better understand this error. Could you send it to me?

@dykandDK The second bug has its own issue right now. See issue #75

**Comment by jm-73** [comment]
@eavanvalkenburg 
Put this in your config.yaml

```
logger:
  default: critical 
  logs: 
    custom_components.indego: debug 
    pyIndego: debug 
```

**Comment by jm-73** [comment]
Will close this if I dont get any log soon!

**Comment by eavanvalkenburg** [comment]
Sorry, missed your comments, will pull together ligging tomorrow

**Comment by eavanvalkenburg** [comment]
Running logs now, don't see this error coming back, but I did upgrade to 1.3 so maybe a fix was in there?

**Comment by jm-73** [comment]
Constantly detecting bugs and making improvements. Maybe the error is gone. Please post a new issue if the problems come back. And make a debug log.
