### ISSUE TITLE
Bug in old debug code

### ISSUE THREAD

**Issue by jm-73** [jm-73/Indego#75]
https://github.com/dykandDK wrote:

I'm seeing a similar error after upgrading to version 1.2:

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 295, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 446, in _async_add_entity
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 297, in async_write_ha_state
    self._async_write_ha_state()  # type: ignore
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    state = self.state
  File "/config/custom_components/indego/sensor.py", line 256, in state
    if (self._IAPI._battery_percent > self._battery_percent_max):
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'

_Originally posted by @dykandDK in https://github.com/jm-73/Indego/issues/74#issuecomment-643327842_

**Comment by jm-73** [comment]
This bug has some code that i recently removed. It  is old debug code that sometimes causes crashes. The code is removed and better error handling implemented. Will be in next release.

**Comment by jm-73** [comment]
Implemented in 1.3
