### ISSUE TITLE
Setup error afer update 2.0

### ISSUE THREAD

**Issue by Olum-hack** [jm-73/Indego#91]
Hello,

I get an error now after the update to 2.0

Logger: homeassistant.setup
Source: custom_components/indego/__init__.py:165
First occurred: 19:58:42 (1 occurrences)
Last logged: 19:58:42

Error during setup of component indego
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 190, in _async_setup_component
    result = await asyncio.wait_for(task, SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/indego/__init__.py", line 61, in setup
    Mower()
  File "/config/custom_components/indego/__init__.py", line 165, in __init__
    Indego.update_last_completed_mow()
  File "/usr/local/lib/python3.7/site-packages/pyIndego/indego_client.py", line 68, in update_last_completed_mow
    self.get(f"alms/{self._serial}/predictive/lastcutting")
  File "/usr/local/lib/python3.7/site-packages/pyIndego/indego_base_client.py", line 104, in _update_last_completed_mow
    self.last_completed_mow = convert_bosch_datetime(new["last_mowed"])
  File "/usr/local/lib/python3.7/site-packages/pyIndego/helpers.py", line 26, in convert_bosch_datetime
    tmp = '{:%Y-%m-%d %H:%M}'.format(datetime.fromisoformat(boschdatetime))
ValueError: Invalid isoformat string: '2020-06-19T13:09:57.15+02:00'

**Comment by jm-73** [comment]
This is going to be fixed in 3.0

**Comment by Olum-hack** [comment]
Thats in Log for Version 3.0

2020-06-24 21:55:35 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/indego/__init__.py", line 309, in _initial_update
    await self.refresh_5m(_)
  File "/config/custom_components/indego/__init__.py", line 357, in refresh_5m
    self._update_next_mow(),
  File "/config/custom_components/indego/__init__.py", line 469, in _update_last_completed_mow
    await self.indego.update_last_completed_mow()
  File "/usr/local/lib/python3.7/site-packages/pyIndego/indego_async_client.py", line 77, in update_last_completed_mow
    await self.get(f"alms/{self._serial}/predictive/lastcutting")
  File "/usr/local/lib/python3.7/site-packages/pyIndego/indego_base_client.py", line 105, in _update_last_completed_mow
    self.last_completed_mow = convert_bosch_datetime(new["last_mowed"])
  File "/usr/local/lib/python3.7/site-packages/pyIndego/helpers.py", line 26, in convert_bosch_datetime
    return datetime.fromisoformat(boschdatetime)
ValueError: Invalid isoformat string: '2020-06-19T13:09:57.15+02:00'

**Comment by jm-73** [comment]
Will be corrected in 3.0
